services:
  api:
    build: ./backend
    container_name: whoami-api
    env_file:
     - .env
    ports:
     - "${APP_PORT}:8000"
    volumes:
      - whoami_data:/data
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: whoami-bot
    env_file: .env
    depends_on:
      - api

volumes:
  whoami_data:
